images:
  image:
    repository: ghcr.io/sempersupra/garm-appliance@sha256
    tag: 6e54a4c39b88266196971fc20e62d603b4d670100b827ff534edfe0cbeb6f9b0

consts:
  controller_container_name: garm
  seed_container_name: garm-config-seed
  config_path: /etc/garm
  config_file: /etc/garm/config.toml
  seed_config_path: /seed/config.toml
  tls_certificate_path: /garm-tls.crt
  tls_private_key_path: /garm-tls.key
  internal_https_port: 8080
