app_name: rdte-t6-foliorelay
printer_name: FolioRelay
printer_location: RDTE
public_host: foliorelay-t6.local
management_port: 18443
management_scheme: https
management_internal_port: 18080
ipp_port: 8634
data_root: /mnt/rdtepool/foliorelay-t6
token_file: /mnt/rdtepool/foliorelay-t6/secrets/control.token
control_image: ghcr.io/sempersupra/foliorelay-control@sha256:d0ba6d1efbed0d9f84b20d374eeb44ee28ab0874a683396e628850f159193cf5
cups_image: ghcr.io/sempersupra/foliorelay-cups@sha256:0997ad2054ca5e57f34291372aed55f549eee9ff201f171b430436b0655c0814
