images:
  image:
    repository: ghcr.io/sempersupra/litellm-appliance@sha256
    tag: 225c899db85865929f6099d3e1fe27097cafaed5af823fa397e75e1eb6ec51ac

consts:
  container_name: litellm
  config_dir: /config
  config_file: /config/proxy_server_config.yaml
  secret_dir: /run/secrets/semper-env
  internal_web_port: 4000
